[package]
name = "sherlog"
version = "0.1.0"
authors = ["Benjamin Richner"]
edition = "2018"
license = "GPLv3"

[dependencies]
cairo-rs = "0.9.1"
gdk = "0.13.2"
gio = "0.9.1"
glib = "0.10.1"
gtk = "0.9.2"
gtk-sys = "0.10.0"
gobject-sys = "0.10.0"
log = "0.4.11"
chrono = "0.4.15"
regex = "1.3.9"
zip = { git = "https://github.com/BenjaminRi/zip-rs.git", branch = "pkzip-cipher", version = "0.5", features = ["deflate"], default-features = false }