[package]
name = "sherlog"
version = "0.1.0"
authors = ["Benjamin Richner"]
edition = "2018"
license = "GPLv3"

[dependencies]
cairo-rs = "0.8.1"
gdk = "0.12.1"
gio = "0.8.1"
glib = "0.9.3"
gtk = "0.8.1"
gtk-sys = "0.9.2"
gobject-sys = "0.9.1"
log = "0.4.8"
chrono = "0.4.11"
regex = "1.3.7"
zip = { git = "https://github.com/BenjaminRi/zip-rs.git", branch = "pkzip-cipher", version = "0.5", features = ["deflate"], default-features = false }