[package]
name = "sherlog"
version = "0.8.2"
authors = ["Benjamin Richner"]
edition = "2018"
license = "GPL-3.0-only"
description = "Log viewer and analysis tool"
keywords = ["visualization", "log", "analyzer", "debug-tool"]
categories = ["visualization", "parser-implementations"]
repository = "https://github.com/BenjaminRi/Sherlog/"

[package.metadata.winres]
ProductName = "Sherlog"
OriginalFilename = "sherlog.exe"
LegalCopyright = "Copyright © 2020 Benjamin Richner"

[dependencies]
cairo-rs = "0.14.0"
gdk = "0.14.0"
gio = "0.14.0"
glib = "0.14.0"
gtk = "0.14.0"
gtk-sys = "0.14.0"
gobject-sys = "0.14.0"
log = "0.4.11"
chrono = "0.4.15"
regex = "1.3.9"
zip = { version = "0.5.9", features = ["deflate"], default-features = false }
[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
