[package]
name = "sherlog"
version = "0.1.0"
authors = ["Benjamin Richner"]
edition = "2018"
license = "GPLv3"

[dependencies]
gtk = "0.7.0"
gio = "0.7.0"
glib = "0.8.2"
log = "0.4"
chrono = "0.4"
zip = { git = "https://github.com/BenjaminRi/zip-rs.git", branch = "pkzip-cipher", version = "0.5", features = ["deflate"], default-features = false }