[package]
name = "sherlog"
version = "0.1.0"
authors = ["Benjamin Richner"]
edition = "2018"
license = "GPLv3"

[dependencies]
gtk = "0.8.0"
gdk = "0.12.0"
gio = "0.8.0"
glib = "0.9.1"
log = "0.4.8"
chrono = "0.4.10"
regex = "1.3.4"
gtk-sys = "0.9.2"
cairo-rs = "0.8.0"
gobject-sys = "0.9.1"
zip = { git = "https://github.com/BenjaminRi/zip-rs.git", branch = "pkzip-cipher", version = "0.5", features = ["deflate"], default-features = false }