[package]
name = "sherlog"
version = "0.7.0"
authors = ["Benjamin Richner"]
edition = "2018"
license = "GPLv3"
description = "Log viewer and analysis tool"
keywords = ["visualization", "log", "analyzer", "debug-tool"]
categories = ["visualization", "parser-implementations"]

[package.metadata.winres]
ProductName = "Sherlog"
OriginalFilename = "sherlog.exe"
LegalCopyright = "Copyright © 2020 Benjamin Richner"

[dependencies]
cairo-rs = "0.9.1"
gdk = "0.13.2"
gio = "0.9.1"
glib = "0.10.1"
gtk = "0.9.2"
gtk-sys = "0.10.0"
gobject-sys = "0.10.0"
log = "0.4.11"
chrono = "0.4.15"
regex = "1.3.9"
zip = { version = "0.5.7", features = ["deflate"], default-features = false }
[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
