[package]
name = "sherlog"
version = "0.8.3"
authors = ["Benjamin Richner"]
edition = "2018"
license = "GPL-3.0-only"
description = "Log viewer and analysis tool"
keywords = ["visualization", "log", "analyzer", "debug-tool"]
categories = ["visualization", "parser-implementations"]
repository = "https://github.com/BenjaminRi/Sherlog/"

[package.metadata.winres]
ProductName = "Sherlog"
OriginalFilename = "sherlog.exe"
LegalCopyright = "Copyright © 2020 Benjamin Richner"

[dependencies]
cairo-rs = "0.15.6"
gdk = "0.15.4"
gio = "0.15.6"
glib = "0.15.6"
gtk = "0.15.4"
gtk-sys = "0.15.3"
gobject-sys = "0.15.5"
log = "0.4.14"
chrono = "0.4.19"
regex = "1.5.4"
zip = { version = "0.5.9", features = ["deflate"], default-features = false }
[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"
